/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u2a1_robertchen;

/**
 *
 * @author 335091559
 */
public class VehicleApp extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle
     */
    int passengerNum, vehicleNumber = 0;
    double distance, gasPrice, passengerFare, fuelEfficiency;
    public VehicleApp() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        distancePrompt = new javax.swing.JLabel();
        distanceInput = new javax.swing.JTextField();
        gasPricePrompt = new javax.swing.JLabel();
        passengerNumberPrompt = new javax.swing.JLabel();
        passengerNumber = new javax.swing.JTextField();
        gasCost = new javax.swing.JTextField();
        passengerCostPrompt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        passengerCost = new javax.swing.JTextField();
        fuelEfficiencyPrompt = new javax.swing.JLabel();
        vehicleFuelEfficiency = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 255));
        title.setText("Vehicle App");

        distancePrompt.setText("Enter the distance the vehicle has travelled (km):");

        distanceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceInputActionPerformed(evt);
            }
        });

        gasPricePrompt.setText("Gas Price:");

        passengerNumberPrompt.setText("Enter the number of pasengers in the vehicle:");

        passengerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerNumberActionPerformed(evt);
            }
        });

        passengerCostPrompt.setText("Enter the cost for each passenger ($):");

        output.setEditable(false);
        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        fuelEfficiencyPrompt.setText("Enter the fuel efficiency:");

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(56, 56, 56)
                .addComponent(gasPricePrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gasCost, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passengerNumberPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passengerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passengerCostPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passengerCost, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(distancePrompt)
                        .addGap(18, 18, 18)
                        .addComponent(distanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fuelEfficiencyPrompt)
                        .addGap(18, 18, 18)
                        .addComponent(vehicleFuelEfficiency, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirm)
                        .addGap(20, 20, 20)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gasPricePrompt)
                            .addComponent(gasCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerNumberPrompt)
                    .addComponent(passengerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distancePrompt)
                    .addComponent(distanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerCostPrompt)
                    .addComponent(passengerCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(confirm)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelEfficiencyPrompt)
                    .addComponent(vehicleFuelEfficiency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distanceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceInputActionPerformed
//        distanceTravelled = Integer.parseInt(distanceInput.getText());
    }//GEN-LAST:event_distanceInputActionPerformed

    private void passengerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerNumberActionPerformed
//        passengerAmount = Integer.parseInt(passengerNumber.getText());
    }//GEN-LAST:event_passengerNumberActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        try {
            vehicleNumber ++;
            distance = Double.parseDouble(distanceInput.getText());
            gasPrice = Double.parseDouble(gasCost.getText());
            passengerNum = Integer.parseInt(passengerNumber.getText());
            passengerFare = Double.parseDouble(passengerCost.getText());
            fuelEfficiency = Double.parseDouble(vehicleFuelEfficiency.getText());
            Vehicle vehicle = new Vehicle(distance, passengerNum, passengerFare, fuelEfficiency, gasPrice);
            output.append("Vehicle " + Integer.toString(vehicleNumber) + ":\n");
            output.append("Distance travelled: " + Double.toString(vehicle.setDistance(distance)) + "\n");
            output.append("Number of passengers: " + Integer.toString(vehicle.setPassengerNum()) + "\n");
            output.append("Cost per passenger: " + Double.toString(vehicle.setPassengerFare()) + "\n");
            output.append("Fuel efficiency: " + Double.toString(vehicle.setFuelEfficiency()) + "\n");
            output.append("Gas price: " + Double.toString(vehicle.setGasPrice()) + "\n\n");
//            output.append(Double.toString(vehicle.revenue()) + "\n");
//            output.append(Double.toString(vehicle.totalCost(distance)) + "\n");
//            output.append(Double.toString(vehicle.totalProfit(distance)) + "\n");
        }
        catch (Exception e) {
            output.setText("Invalid input. Please make sure all fields are filled out and all fields have a proper input.");
        }
    }//GEN-LAST:event_confirmActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JTextField distanceInput;
    private javax.swing.JLabel distancePrompt;
    private javax.swing.JLabel fuelEfficiencyPrompt;
    private javax.swing.JTextField gasCost;
    private javax.swing.JLabel gasPricePrompt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField passengerCost;
    private javax.swing.JLabel passengerCostPrompt;
    private javax.swing.JTextField passengerNumber;
    private javax.swing.JLabel passengerNumberPrompt;
    private javax.swing.JLabel title;
    private javax.swing.JTextField vehicleFuelEfficiency;
    // End of variables declaration//GEN-END:variables
}
